name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 16 * * *' # Runs at 12am Asia/Taipei

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: 'zh_Hant_TW'
          SHOW_UPDATED_DATE: 'True'
          UPDATED_DATE_FORMAT: '%Y/%m/%d'
          SHOW_LINES_OF_CODE: 'True'
          SHOW_TOTAL_CODE_TIME: 'True'
          SHOW_LANGUAGE: 'True'
          SHOW_TIMEZONE: 'True'
          SHOW_LANGUAGE_PER_REPO: 'True'
